### PR TITLE
Document failing search for unactivated language. close #667

### LINKED ISSUE #667: Document failing search for unactivated language
Search for language not activated in merchant center fails

* [ ] add to troubleshooting guide with example
* [ ] fail project endpoint test if the correct language is not activated

### PR DESCRIPTION
**Pull request by schleichardt**
@lauraluiz please review

### CODE REVIEW

File: src/main/java/io/sphere/sdk/meta/TroubleshootingGuide.java [hunk 1]
```diff
@@ -127,7 +127,11 @@
 
  <p>If you get do not get an exception, it may be of importance to know your JVM SDK version, Java version, date of occurrence and operating system.</p>
  Describe the behavior you observed and the one you would like to obtain.
-
+ <h3 id="product-not-found-by-text">Product not found</h3>
+ <ul>
+    <li>Maybe the product is not published. See {@link io.sphere.sdk.products.commands.updateactions.Publish}.</li>
+    <li>The product was not found for the search because the locale was not activated for search. Enable it in the Merchant Center.</li>
```
Comment (lauraluiz) [inline src/main/java/io/sphere/sdk/meta/TroubleshootingGuide.java]: What do you mean with "locale not being activated for search"? Sounds like for every language you can choose whether to make them "searchable" or not, but I guess that's not it.

File: sphere-common/src/main/java/io/sphere/sdk/search/SearchDsl.java [hunk 2]
```diff
@@ -8,14 +8,14 @@
...
-     * @param text the new search text with locale
+     * @param text the new search text with locale, the locale should be enabled for search (see the project settings in the Merchant Center)
      * @return a new object with {@code text}
      */
     C withText(final LocalizedStringEntry text);
 
     /**
      * Returns a new object with the new text as search text.
-     * @param locale the new locale
+     * @param locale the new locale, the locale should be enabled for search (see the project settings in the Merchant Center)
```
Comment (lauraluiz) [inline sphere-common/src/main/java/io/sphere/sdk/search/SearchDsl.java]: Also review, since the sentence sounds confusing.
